### ISSUE TITLE
rust-minidump mishandling windows 10 x64 minidump's cpu context?

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#162]
Looking at [this firefox crash](https://crash-stats.mozilla.org/report/index/8ef896d4-0704-45b7-979a-3bae10210511#tab-rawdump) in minidump-processor with

`cargo run --release -- --human --symbols-url=https://symbols.mozilla.org/ --symbols-cache=/tmp/symbols/cache --verbose=trace ~/Downloads/test-dumps/windows/8ef896d4-0704-45b7-979a-3bae10210511-upload_file_minidump.dmp`

We get wildly different results for the CPU Context's registers than soccorro does (which in turn makes the backtraces garbage):

Soccorro reports:

```
    "r10": "0x00000034c67fdbb8",
    "r11": "0x000001980a3a6880",
    "r12": "0x0000000000000000",
    "r13": "0x00007ff8187a1870",
    "r14": "0x00000034c67fdc10",
    "r15": "0x0000000000000000",
    "r8": "0x00000034c67fdbb8",
    "r9": "0x00000034c67fdad0",
    "rax": "0x00009a69cdaeaf6d",
    "rbp": "0x000001987b14e240",
    "rbx": "0x000001980a878380",
    "rcx": "0x0000000000000000",
    "rdi": "0x00000034c67fdbb8",
    "rdx": "0x00000034c67fdad0",
    "rip": "0x00007ff814ac017e",
    "rsi": "0x00000034c67fdad0",
    "rsp": "0x00000034c67fd9c0"
```

While minidump-processor reports:

```
    rax = 0x0000000000000004   rdx = 0x0000000000000000
    rcx = 0x00000000000004e4   rbx = 0x0000000000000000
    rsi = 0x0000000000000000   rdi = 0x00000000000004e4
    rbp = 0x00000034c67ffe80   rsp = 0x00000034c67fc868
     r8 = 0x000000007ffe0384    r9 = 0x0000000000000000
    r10 = 0x00007ff86758e34c   r11 = 0xffff81a013744ef0
    r12 = 0xffffffffffffffff   r13 = 0x00007ff86762d7b8
    r14 = 0x00000000000004e4   r15 = 0x00000034c67fcb40
    rip = 0x00007ff86998cda4
```

Some of the values are kinda similar but honestly that just makes it more perplexing -- e.g. rsp: `0x00000034c67fd9c0` vs `0x00000034c67fc868`.

I'm guessing there's a format difference or something for this version of windows but I have no idea what it could be (is this a misc_info_5 thing...? would it have More Accurate values for redundant registers..?).

**Comment by gabrielesvelto** [comment]
I had a look at how Breakpad does this and the difference stems from the fact that the context appearing in minidump_stackwalk output is not the context of the crashing thread; it's the context retrieved from the **ExceptionStream**. The crashing thread's context includes the frames of the exception handler itself so minidump_stackwalk doesn't use it because it would pollute the stack trace with them. So minidump_stackwalk prefers using the context from the **ExceptionStream** because that's the context at the point where the crash happened. I knew this but forgot about it; it occurred to me only when I realized that the stack pointer in the **ExceptionStream** context is always at a higher address than the one in the crashing thread.

See [this code and comments](https://searchfox.org/mozilla-central/rev/27722db2f164add7047d7db03169966cb806e927/toolkit/crashreporter/google-breakpad/src/processor/minidump_processor.cc#238-266) in Breakpad for how this happens.
