### ISSUE TITLE
Gather block stats

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#169]
The mozilla schema has two fields I don't think we have the data for yet:

* largest_free_vm_block
* tiny_block_size
* write_combine_size

Haven't yet looked into where in the minidump file they come from.

**Comment by luser** [comment]
[That info gets populated here](https://github.com/mozilla-services/minidump-stackwalk/blob/9a55067a19fc1ba2cd49a39863afb2ab1723e71c/minidump-stackwalk/stackwalker.cc#L921), from the memory info list stream, which we don't currently support reading (#21).

**Comment by gabrielesvelto** [comment]
It's not really useful info, is it? I think I never looked at those fields in all these years.

**Comment by luser** [comment]
bsmedberg added it ages ago when we were having lots of issues with OOM crashes (before we had e10s) and we were getting malformed or empty minidumps because we didn't have enough memory left to write the dump. I suspect that's no longer useful. Also, at some point we started submitting memory reports alongside the dump in low-memory scenarios, which is likely to be way more actionable.

**Comment by Gankra** [comment]
I'm gonna say we're not gonna bother with this one. It relies on the extra json and isn't really useful anymore.
