### ISSUE TITLE
What is the idea behind the FrameWalker trait?

### ISSUE THREAD

**Issue by loewenheim** [luser/rust-minidump#212]
The `symbolic` shim contains [a trait called `FrameWalker`](https://github.com/luser/rust-minidump/blob/1f8cb87df24083d04985ce4db1f045b46faf2c68/minidump-processor/src/symbols.rs#L114) that also exists in `breakpad-symbols`. I have a hard time understanding what the intended implementors of this trait are, and as far as I can tell no type in `breakpad-symbols` implements it. Can you shed some light on this, @Gankra?

**Comment by Gankra** [comment]
The FrameWalker trait is the interface that minidump-processor exposes to the stackwalking implementation for it to query thread/stack state and write out the results of stackwalking. (But it's declared in breakpad-symbols and the symbolic-shim because the dependency chain is inverted.)

The implementation of the trait is [here](https://github.com/luser/rust-minidump/blob/master/minidump-processor/src/stackwalker/mod.rs#L22-L80). And it's fed into the SymbolProvider [here](https://github.com/luser/rust-minidump/blob/master/minidump-processor/src/stackwalker/arm64.rs#L211) (and in all the other platform-specific impls).

You don't need to implement it, you just get to use it in your impl of SymbolProvider::walk_frame.

**Comment by Gankra** [comment]
Oh there's also a [mock FrameWalker](https://github.com/luser/rust-minidump/blob/master/breakpad-symbols/src/sym_file/walker.rs#L868-L906) and huge pile of tests in breakpad-symbols in case you want to steal that code for the symbolic impl.
