### ISSUE TITLE
Create a proper abstraction for linux os strings

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#272]
In handling all the Linux* streams I absentmindedly parsed everything as utf8 since I know that's ~basically true. But things like paths (which are a lot of the values we process) are technically just "arbitrary bytes", so we should have a proper LinuxOsString abstraction for the output and do the parsing/matching on byte-strings.

Right now nothing *bad* will happen if this assumption is broken. We'll just fail to parse whatever data we're reading and come back with default/empty values for the stream. Just a quality of implementation thing, and probably not one that will come up often (since non-utf8 paths are hard to make in the first place).

**Comment by luser** [comment]
There are times where I wish Rust exposed some of its platform-specific primitives for use in cross-platform code, like how Python provides [both `PosixPath` and `WindowsPath` types](https://docs.python.org/3/library/pathlib.html#concrete-paths) everywhere.

It would be handy to be able to reuse the POSIX `std::ffi::OsString` implementation here, since those are the exact semantics you want.

**Comment by Gankra** [comment]
Weirdly I don't think OsString would have been that useful since it *also* refuses to have any kind of string search/manipulation API. So all the code I wrote for this ends up being stuff I needed to do anyway.
