### ISSUE TITLE
module casing does not match socorro?

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#281]
```
socc-pair --crash-id=d34af050-9aa7-4efe-b61d-e94e20211103
```

reports this mysterious difference:

```diff
         33: {
           file: hg:hg.mozilla.org/releases/mozilla-release:accessible/ipc/win/handler/AccessibleHandler.cpp:08b69dc588fbdd88334ebcb6fa303eec95176cd6
           frame: 33
           function: mozilla::a11y::AccessibleHandler::get_accChild(tagVARIANT, IDispatch**)
           function_offset: 0x00000126
           line: 735
-          did not match
+          module: accessiblehandler.dll
-          module: AccessibleHandler.dll
           module_offset: 0x000023a6
           offset: 0x7ffe884a23a6
           trust: cfi
         }
```

(the line marked with + is always what socorro had)

**Comment by gabrielesvelto** [comment]
I'd say this is an issue in the old stackwalker. The correct name which is stored in the dump is `AccessibleHandler.dll`. The symbol also uses this capitalization (see [here](https://symbols.mozilla.org/try/AccessibleHandler.pdb/ECDFD1DF36E588144C4C44205044422E1/AccessibleHandler.sym)). So rather than an issue this is an improvement.

**Comment by Gankra** [comment]
I am inclined to agree, my only concern is if some downstream logic is relying on case differences getting folded away to do *something* (no idea what it would be).

**Comment by Gankra** [comment]
but sure let's call it an improvement until proven otherwise :)
