### ISSUE TITLE
haunted modules/code_ids on linux and macos?

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#283]
socc_pair --crash-id=422d8af0-1681-45f4-a290-cd8120211109

```diff
     0: {
       base_addr: 0x7fda0a909000
       code_id: e208b29f35421147499a89d029d117efe99bdc81
       debug_file: libpixbufloader-svg.so
       debug_id: 9FB208E242354711499A89D029D117EF0
       end_addr: 0x7fda0a90e000
       filename: libpixbufloader-svg.so
       version: null
     }

     102: {
       base_addr: 0x7fda18e17000
-      did not match
+      code_id: id
-      code_id: 000000001000
       debug_file: 
       debug_id: 
       end_addr: 0x7fda18e18000
       filename: user
~      ignoring field missing_symbols: true
       version: null
     }

...

     202: {
       base_addr: 0x7fd9f8dff000
-      did not match
+      code_id: id
-      code_id: 000000004000000
       debug_file: 
       debug_id: 
       end_addr: 0x7fd9fcdff000
       filename: memfd:pulseaudio (deleted)
~      ignoring field missing_symbols: true
       version: null
     }
```

Something weird going on with magic modules on linux?

(the line marked with + is always what socorro had)

**Comment by luser** [comment]
There's a goofy fallback case in Breakpad where it returns `"id"` if a module doesn't have useful info attached:
https://chromium.googlesource.com/breakpad/breakpad/+/fe35cd43f2c7386704837b686f91a4e3c882664d/src/processor/minidump.cc#2034

We shouldn't replicate *that* behavior, but it'd be fine to leave these out if we don't have the info for them. We *shouldn't* have that info, since they're not ELF files.

**Comment by Gankra** [comment]
hmm, what values are rust-minindump extracting here? ~uninitialized memory? something else?

**Comment by luser** [comment]
> hmm, what values are rust-minindump extracting here? ~uninitialized memory? something else?

Extremely unlikely, there's no `unsafe` code here except for creating the `mmap` to load a file. Take a look at that dump with `minidump_dump` and see what that module contains?

**Comment by Gankra** [comment]
(to be clear by "~uninitialized" I meant meaningless memory in the minidump writer that got written to the minidump absent a real value)

**Comment by luser** [comment]
Huh, this appears to be a long-standing bug in the Breakpad client code! `MinidumpWriter::FillRawModule` is the code that takes the list of mappings (from `/proc/self/maps`) and fills in an `MDRawModule` for each. If there isn't a caller-provided ID for the module (I believe we implemented that so we could dump the Build IDs for Android libraries at runtime, before Breakpad learned how to handle the custom dynamic linker Firefox was using), it calls `LinuxDumper::ElfFileIdentifierForMapping` to attempt to find an ELF Build ID or fall back to a silly hash of the first page of the text section. But note that `ElfFileIdentifierForMapping` returns a `bool` for success, and this code ignores the result:
https://searchfox.org/mozilla-central/rev/a48e21143960b383004afa9ff9411c5cf6d5a958/toolkit/crashreporter/breakpad-client/linux/minidump_writer/minidump_writer.cc#647

That function calls `FileID::ElfFileIdentifierFromMappedFile`:
https://searchfox.org/mozilla-central/rev/a48e21143960b383004afa9ff9411c5cf6d5a958/toolkit/crashreporter/breakpad-client/linux/minidump_writer/linux_dumper.cc#351

Which will, in order, try `FindElfBuildIDNote` and if that fails, `HashElfTextSection`:
https://searchfox.org/mozilla-central/rev/a48e21143960b383004afa9ff9411c5cf6d5a958/toolkit/crashreporter/google-breakpad/src/common/linux/file_id.cc#147

The modules in your diff output are clearly not shared libraries (one of them is `memfd:pulseaudio`), so they're winding up in `HashElfTextSection`, and the first thing that function does is resize the output vector to the size of a GUID:
https://searchfox.org/mozilla-central/rev/a48e21143960b383004afa9ff9411c5cf6d5a958/toolkit/crashreporter/google-breakpad/src/common/linux/file_id.cc#123

…and even though it returns `false` because it won't find a text section in a non-ELF mapping, since `FillRawModule` doesn't check the result, but instead checks that the length of the output `identifier` vector is non-zero, it'll just write whatever bytes are in there:
https://searchfox.org/mozilla-central/rev/a48e21143960b383004afa9ff9411c5cf6d5a958/toolkit/crashreporter/breakpad-client/linux/minidump_writer/minidump_writer.cc#653

> (to be clear by "~uninitialized" I meant meaningless memory in the minidump writer that got written to the minidump absent a real value)

You get a gold star for correctly explaining this unexpected output: :star2: :grin: .

**Comment by luser** [comment]
Unfortunately you (or someone else at Mozilla) has to fix this in the Firefox client code. I suspect it's not very harmful, despite reading uninitialized memory, since the memory is in an `auto_wasteful_vector`, so it's on the current stack, which isn't going to have any particularly sensitive information laying around:
https://searchfox.org/mozilla-central/rev/a48e21143960b383004afa9ff9411c5cf6d5a958/toolkit/crashreporter/google-breakpad/src/common/memory_allocator.h#230

I will admit to writing that `auto_wasteful_vector` class in a past life, and I suspect that for correctness it ought to be zero-initializing its `stackdata_` member, but unfortunately, as you already know, C++.

**Comment by Gankra** [comment]
Ok I think I'm happy to call this an upstream issue (which has been fixed for linux). I see no reason to regard the breakpad output of "id" any better than us just honestly reporting the contents.
