### ISSUE TITLE
Merge minidump_dump into minidump-stackwalk

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#304]
~~While I have little love for minidump_dump, it has its uses and should be something you can `cargo install` and whatnot. That means pulling it out to be its own top-level crate just like minidump-stackwalk.~~

Merge minidump_dump's code into minidump-stackwalk as another output format (--raw-dump):

minidump_dump is here:

https://github.com/luser/rust-minidump/blob/master/minidump/src/bin/minidump_dump.rs

A new --raw-dump flag should be added, based on `--json`: https://github.com/luser/rust-minidump/blob/2dc7ecc384f8ed123387cace30157c5288b6b5f3/minidump-stackwalk/src/main.rs#L33-L40

Add it to the arg group as well: https://github.com/luser/rust-minidump/blob/2dc7ecc384f8ed123387cace30157c5288b6b5f3/minidump-stackwalk/src/main.rs#L66-L68

Incorporate it into the logic that disabled the implicit --human flag: https://github.com/luser/rust-minidump/blob/2dc7ecc384f8ed123387cace30157c5288b6b5f3/minidump-stackwalk/src/main.rs#L347-L348

Copy minidump_dump's code into a new function and call it here if that's the right output format: https://github.com/luser/rust-minidump/blob/2dc7ecc384f8ed123387cace30157c5288b6b5f3/minidump-stackwalk/src/main.rs#L374

Be sure to hoist out the output stream logic so that --output-file works right: https://github.com/luser/rust-minidump/blob/2dc7ecc384f8ed123387cace30157c5288b6b5f3/minidump-stackwalk/src/main.rs#L397-L403

Extra credit: audit if there's any weird interactions with existing flags

Add an `insta` test for the new output, based on this one: https://github.com/luser/rust-minidump/blob/2dc7ecc384f8ed123387cace30157c5288b6b5f3/minidump-stackwalk/tests/test-minidump-stackwalk.rs#L40-L57

Save the new snapshot (I can do this for you if you want):

```
> cargo test (this will fail) 
> cargo install insta (install snapshot review tool)
> cargo insta review (accept)
> cargo test (this should pass now)
```

Then remove minidump_dump.

**Comment by luser** [comment]
Given that it lives in the `minidump` crate right now, it's the only binary you'd get if you ran `cargo install minidump`, right? Maybe that's good enough? There's no other reason to install that crate, and its only real purpose is to exhaustively list the contents of a minidump for investigating weird circumstances.

Alternately, we could split it into its own crate but mark it as non-publishing, and fiddle with our CI configuration to publish pre-built binaries of `minidump-stackwalk` + `minidump_dump` for each release so that folks could easily get a copy of it if desired (and they're not already building all these crates locally).

In any event, I wouldn't expend too many cycles on it. It's useful, but not very broadly.

**Comment by Gankra** [comment]
I have some newfound respect for minidump_dump after doing some more debugging of specific minidumps.

That said I am increasingly inclined to fold it into `minidump-stackwalk` as yet-another-output-format, giving us One Tool To Rule Them All. minidump_dump's code is so trivial it would hardly bloat the binary.

i.e. `minidump-stackwalk --dump` would just be minidump_dump.

**Comment by luser** [comment]
It's incredibly useful for poking at weird and broken minidumps. :) That's a clever idea, I like it! The only reason it exists as a standalone program is because "that's what Breakpad did". If you fold it into mdsw then anyone installing that tool gets it as a free bonus, which is nice! If folks outside of Mozilla wind up using these crates at some point it'd give us a very easy way to ask for more info when they file bugs like "this random minidump I have doesn't produce a stack trace" without going down the potentially-troublesome path of sharing entire minidump files.

**Comment by Gankra** [comment]
Updated the original description, this should now be reasonably accessible to a beginner who wants to learn about minidump-stackwalk's CLI.
