### ISSUE TITLE
Make Symbolizer async

### ISSUE THREAD

**Issue by Gankra** [luser/rust-minidump#327]
Sentry noted that they would prefer symbolication (in minidump-processor) to be async to play nicer with `symbolic`s current APIs. This was originally prototyped in #185 to support compiling everything to wasm, but rejected at the time because things were a bit too early and I was still working out the design of everything.

I see no reason why this isn't possible. Someone just needs to sit down and slap `async` and `await` all over the place.

I don't know if they also need `minidump` itself to be async.

**Comment by Gankra** [comment]
NB probably going to defer this until we land on socorro to avoid 11th hour overhauls.

**Comment by luser** [comment]
> I see no reason why this isn't possible. Someone just needs to sit down and slap `async` and `await` all over the place.

Yeah, that seems straightforward. I guess functionally we'd primarily want to make [`SymbolSupplier::locate_symbols`](https://github.com/luser/rust-minidump/blob/5069ee30611c06ca7672f74cbfa055b089c84880/breakpad-symbols/src/lib.rs#L255) async, and everything that calls it all the way up to `process_minidump`?

I don't think it's worth trying to make anything except locating/fetching/maybe parsing symbols async. Everything else that happens in minidump processing is not even very expensive. I profiled the Breakpad mdsw ages ago and basically 99% of its runtime was parsing `.sym` files, which is probably why the Rust version is faster because even the only-slightly-better-than-a-toy symbol file parser implementation we have here is assuredly way smarter just because it's not stuck using the stone age tools that C++ provides.

I wouldn't overthink this—just pull in `tokio` for `minidump-processor` to use in mdsw (you can always make it optional if you want to revive that wasm work) + whatever async HTTP crate is easiest to use (maybe `reqwests` has an async mode?) for `breakpad-symbols`. Since Sentry will be using the crate as a library they can bring their own runtime, and I'd guess they will bring their own equivalent of `HTTPSymbolProvider` so it doesn't matter much what ours does.

That does make me think that perhaps `HTTPSymbolProvider` should be hoisted up into `minidump-processor` which might make `breakpad-symbols` easier to integrate into `symbolic` anyway.

**Comment by Gankra** [comment]
Yeah reqwest is async by default these days (I use it like that in socc-pair), we're basically flipping the "oh my god I don't want async please go away" switch lol
