### ISSUE TITLE
memory usage for minidump-stackwalk

### ISSUE THREAD

**Issue by willkg** [luser/rust-minidump#355]
Processing this crash report died because of an OOM:

https://crash-stats.allizom.org/report/index/cea2d009-a1af-4964-bd1b-9cad90211213

The stderr is:

```
memory allocation of 268435456 bytes failed
```

Aria looked at the minidump and things seem fine.

However, it kind of looks like rust-minidump minidump-stackwalk uses memory differently than breakpad stackwalker did. I'm seeing spikes in memory usage on the stage processor node:

![image](https://user-images.githubusercontent.com/820826/145832273-65d68aa6-5973-4025-bb45-06c1a0c8f3f9.png)

stage environment has a single processor node which runs one processor process which has 5 threads, so it could be running 5 simultaneous minidump-stackwalk processes.

How much memory should a single minidump-stackwalk process be using? What should Socorro do when it runs out of memory? Should it try it again?

**Comment by Gankra** [comment]
Is this something we can deploy to production without resolving?

**Comment by Gankra** [comment]
Some notes:

I haven't verified but it's almost certain that the overwhelming source of memory usage is symbol loading + parsing (files on the order of 100mb-1gb are standard).

Places where there may be room for easy improvement:

* How we (re)allocate memory during download (will #329 improve this?)
* How we load symbols from the disk cache (do we mmap? can we? should we?)
* How we allocate parsed symbol results (not sure what we could do here specifically but presumably this is linear in the size of the minidump, and split up into different collections. do we hold pointers into the symbol file for strings? can we? should we?)

**Comment by willkg** [comment]
In stage, I see some spikes, but it's pretty infrequent. Maybe one or two spikes every 6 hours. However, stage and prod are different and I can't tell from stage data whether this will be a bigger issue in prod or not.

I think given it's infrequent on stage we should move forward, but I'll keep an eye on it and we can roll back if something goes awry.

**Comment by Gankra** [comment]
#357 might help? I don't have a good setup for measuring memory usage/traffic though.

**Comment by luser** [comment]
n.b.: the symbol parser allocates a `Vec` for the entire contents when it reads a symbol file from disk:
https://github.com/luser/rust-minidump/blob/eb8f13c202d95fc46e5cb8dd557d7e3b903102e1/breakpad-symbols/src/sym_file/parser.rs#L467
(that could definitely be an `mmap`).

The parser is pretty allocation-heavy in general since it returns an owned type and doesn't borrow from the input. e.g. every `FUNC` line allocates a new `String` for the function name:
https://github.com/luser/rust-minidump/blob/eb8f13c202d95fc46e5cb8dd557d7e3b903102e1/breakpad-symbols/src/sym_file/parser.rs#L163

Changing that to borrow from the input would probably help a lot, but might be annoying to deal with API-wise.

**Comment by Gankra** [comment]
I hopped into the tokio discord and got some interesting insights:

* as long as minidump-stackwalk is a one-shot minidump processor and we aren't trying to like, walk every thread in parallel, async is ~useless (and potentially actively harmful for file i/o?)
   * `#[tokio::main(flavor = "current_thread")]` may help with this a bit, it would avoid bouncing things around thread pools we don't need/use.
   * if we run on a linux kernel new enough to have `uring` stuff, this may be mitigated?
* if we manually write a `Read` loop (or in async, `chunk`), that passes data to both cache writing and parsing in pieces, then we should actually be able to write to the cache + parse concurrently with the download, even for reqwest::blocking.
   * and in theory we'd never need to have the whole symbol file in memory *ever*
   * this would necessitate some rearchitecting of the code so that fetch_symbols calls "into" parsing/caching (it already does for caching)
   * unclear how well our ancient version of `nom` supports streaming input
   * unclear if there's a need to keep the whole file around (afaict no, you don't even need to backtrack while parsing breakpad symbol files, I think?)

**Comment by luser** [comment]
> if we manually write a `Read` loop (or in async, `chunk`), that passes data to both cache writing and parsing in pieces, then we should actually be able to write to the cache + parse concurrently with the download, even for reqwest::blocking.

This feels like a lot of work for something that should ultimately all be replaced by `symbolic-symcache`, TBH.

**Comment by Gankra** [comment]
This should be resolved by #359
