### ISSUE TITLE
Question: does this process MS WIndows format or Linux or... ?

### ISSUE THREAD

**Issue by thomasbratt** [luser/rust-minidump#370]
Hi, what is the minidump format? The readme looks like it's running on Linux with linux libraries. The format documentation link goes to a Microsoft page. I'm a bit confused :)

**Comment by flub** [comment]
The format was originally created by microsoft, however since been adopted by crashreporters on all platforms (with some extensions, the format allows for extensions).

**Comment by Gankra** [comment]
Also as a rough approximation, Microsoft still defines and controls the "core" format. (And they have a stake in non-Windows minidumps due to things like Visual Studio Code.)

**Comment by luser** [comment]
The non-Windows portions of the format here were pioneered in [Google's Breakpad library](https://chromium.googlesource.com/breakpad/breakpad/), to which I was a heavy contributor during my time at Mozilla.  It was used for crash reporting in both Firefox and Chrome, as well as numerous other projects. These crates drew heavy design inspiration from Breakpad. Google has since developed a revamped set of client-side libraries called [Crashpad](https://chromium.googlesource.com/crashpad/crashpad/), which they are now using in Chrome on most platforms. Crashpad defined some additional extensions to the format which are also supported by this crate.

**Comment by thomasbratt** [comment]
Thanks all, really appreciate the responses!
