### ISSUE TITLE
Errors do not implement std::error::Error

### ISSUE THREAD

**Issue by jan-auer** [luser/rust-minidump#371]
Several errors implement `failure::Fail` right now, which comes with the added benefit of having a backtrace on stable. How much do you rely on backtraces in your use cases at the moment? I would like to create a PR swapping this all out with `std::error::Error`.

@Gankra @luser

**Comment by Gankra** [comment]
We don't use the backtrace functionality at all (I wasn't aware it existed!).

`failure` was here before I got here, and I had no reason to mess with it. I am probably leaning on it in a few places to grease the wheels of error type conversion (although a lot of places are explicit format_err lines, so, not really helping...) and formatting, but otherwise *shrug*.

The only "load bearing" part of our error infra is that these strings should stay relatively consistent: https://github.com/luser/rust-minidump/pull/356#issuecomment-992573388. Notably everything before the dash (`-`) is stuff we parse and potentially index. Although even there I'm playing a bit fast and loose with that since I didn't put any effort into handling the errors with payloads which presumably will not Debug as just their name.

**Comment by Gankra** [comment]
(Errors in rust-minidump are weird since we largely must limp on in the face of basically every error, so there aren't many places that **don't** ultimately discard them.)
