### ISSUE TITLE
FrameTrust's JSON name differs from symbolic and Sentry

### ISSUE THREAD

**Issue by jan-auer** [luser/rust-minidump#372]
The definition of JSON names for `FrameTrust` in this crate differs from how `symbolic::minidump::processor::FrameTrust` had it defined. I'm looking at adding `serde::{Deserialize, Serialize}` as well as `std::str::FromStr` to this type so it can be used in APIs. 

This would be a convenience factor for us, hence view this as an ask for opinion. Strictly speaking, we should probably not rely on a specific serialization of this type in public APIs. My hope is just that it's not too late to make this change, which would avoid wrapper types :) I absolutely understand if you choose to deny this change.

The differences are:

- `FrameTrust::CfiScan`: `"cfi_scan"` vs `"cfiscan"`
- `FrameTrust::FramePointer`: `"frame_pointer"` vs `"fp"`
- `FrameTrust::None`: `"non"` [sic] vs `"none"`

While at it, I'd also 
- Rename `CallFrameInfo` to `Cfi` to align it with `CfiScan`
- Impl `Default` with `FrameTrust::None`

**Comment by jan-auer** [comment]
@Gankra on Discord:

> Note that the JSON schema is Stabilized (even though we're not 1.0) so I would frown upon breaking it for minor reasons like the "trust" names

I'm happy to shim this on our end, in that case. Still leaving the issue open for the final 2 points from the original post.

**Comment by Gankra** [comment]
This is in reference to this function: https://github.com/luser/rust-minidump/blob/ccef1ac4f2c7d4b58d8cc6023667073db5e4ecd4/minidump-processor/src/process_state.rs#L216-L225

As far as I know, none of these variants can currently show up in output (they just exist because we stubbed them out based on breakpad). They certainly aren't documented in the schema. So they can have their names freely changed:

* prewalked
* cfi_scan
* non

I am personally inclined to just delete all 3 of these variants since they're dead code, but ymmv. That said None I guess is maybe useful for things like Default.

**Comment by Gankra** [comment]
Changing CallFrameInfo to Cfi is "fine". I could take it or leave it.

**Comment by willkg** [comment]
In Socorro, I can write a processor rule that migrates from an older schema version to a new schema version, if that helps. I'm pretty flexible.

**Comment by jan-auer** [comment]
Thanks for the info, in that case I'll create a PR and add them to the documentation. 

It's definitely worth preserving the current variants. We rely on both `None` and `PreWalked` in our case since we pre-walk the stack trace on the client and add it into a custom section on the minidump.

**Comment by flub** [comment]
I think this is fine to close, we have our own FrameTrust type in symbolicator now for our serde/json output and map between.  Also that one implements Default which is the only reason that was interesting to have, Default on the stand-alone type is less clear how useful this is.
