### ISSUE TITLE
schema suggests mac_crash_info is always a record, but it can be null

### ISSUE THREAD

**Issue by willkg** [luser/rust-minidump#385]
In the schema here:

https://github.com/luser/rust-minidump/blame/master/minidump-processor/json-schema.md#L464

It seems to suggest (or at least, this is how I'm reading it) that the `mac_crash_info` value will always be a record. However, I'm seeing cases where the value is `null`:

https://crash-stats.mozilla.org/report/index/1d76dd3c-a756-4a8f-8785-f7bde0220105

I'm seeing similar for `lsb_release`, too.

How do we want to denote this in the schema? Maybe wrap the record in an `Optional`? Maybe add a comment like "yo, homies--this could be the nullz!"?

**Comment by Gankra** [comment]
In my mind "everything can be null" applies not just to leaves of the schema, but to everything, but perhaps I should be more clear on this.

**Comment by Gankra** [comment]
I've tried to make the schema more clear about this here: https://github.com/luser/rust-minidump/commit/7731bad013a9e3ebdd94859eab38756df5c2b624?short_path=f56b800#diff-f56b8000c30ee7bb8c4552612fbb5fca2e1be585ea5fae595fc64cb80aa57a32

Assuming this is good enough and closing, but feel free to argue otherwise.
